# Generated by Django 5.1.4 on 2025-01-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
