# Generated by Django 5.1.4 on 2025-01-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sites_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='sites/'),
        ),
    ]
