# Generated by Django 5.1.4 on 2025-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_page_delete_about_delete_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
