# Generated by Django 5.1.4 on 2025-02-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_query_send_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Enquiry',
        ),
    ]
