# Generated by Django 5.1.4 on 2025-02-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_query_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery_image/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gallery')),
            ],
        ),
    ]
