# Generated by Django 5.1.4 on 2025-02-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_gallery_alter_enquiry_message_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
