# Generated by Django 5.1.4 on 2025-02-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_enquiry_email_alter_enquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='detail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
