# Generated by Django 5.1.4 on 2025-02-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subplan_subfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfeature',
            name='detail',
        ),
    ]
