# Generated by Django 5.1.4 on 2025-02-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_subfeature_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfeature',
            name='suplan',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='subplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan'),
        ),
    ]
