# Generated by Django 5.1.4 on 2025-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_subfeature_suplan_alter_subfeature_subplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlight_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
