# Generated by Django 5.1.4 on 2025-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_subplan_highlight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfeature',
            name='unique',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
