# Generated by Django 5.1.4 on 2025-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subfeature_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfeature',
            name='subplan',
        ),
        migrations.RemoveField(
            model_name='subfeature',
            name='unique',
        ),
        migrations.RemoveField(
            model_name='subfeature',
            name='suplan',
        ),
        migrations.AddField(
            model_name='subfeature',
            name='suplan',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
