# Generated by Django 5.1.4 on 2025-02-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_subfeature_subplan_remove_subfeature_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subfeature',
            old_name='suplan',
            new_name='subplan',
        ),
    ]
