# Generated by Django 5.1.4 on 2025-02-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_subplan_max_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='max_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_month', models.IntegerField()),
                ('total_discount', models.IntegerField()),
                ('subplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subplan')),
            ],
        ),
    ]
