# Generated by Django 5.1.4 on 2025-04-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read_by',
            new_name='read_by_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
