# Generated by Django 5.1.4 on 2025-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_notifyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AlterField(
            model_name='notifyuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
