# Generated by Django 5.1.4 on 2025-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_notification_status_alter_notifyuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
