# Generated by Django 5.2 on 2025-05-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_assignsubcribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubcribers',
            name='subcriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscribers'),
        ),
    ]
