# Generated by Django 5.1.4 on 2025-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_assignsubcribers_subcriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='validity_days',
            field=models.IntegerField(null=True),
        ),
    ]
