# Generated by Django 5.2 on 2025-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignsubcribers',
            options={'verbose_name_plural': 'Assign Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='fqa',
            options={'verbose_name_plural': 'FQAs'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notifyuser',
            options={'verbose_name_plural': 'Notify Users'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='plandiscount',
            options={'verbose_name_plural': 'Package Discounts'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='subfeature',
            options={'verbose_name_plural': 'Subscription Features'},
        ),
        migrations.AlterModelOptions(
            name='subplan',
            options={'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainers'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='youtube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
