# Generated by Django 5.2 on 2025-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_trainer_salary_trainersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersalary',
            name='amount',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
