# Generated by Django 5.2 on 2025-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_trainersalary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersalary',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
